<span style="font-family: Calibri; font-size: 14px;"> 
<strong>
Python 3.12.2
</strong>
</span>

In [1]:
import pandas as pd
import pyodbc

from sqlalchemy import create_engine
from sqlalchemy import text

<span style="font-family: Calibri; font-size: 14px;"> 
<strong>
Current data model 
</strong><br>
Importing CSV Files to Dataframes <br>
</span>

In [62]:
accounts = pd.read_csv("accounts/part-00000-tid-2834924781296170616-a9b7a53c-b8f1-417c-876b-22ce8ab4c825-11024507-1-c000.csv", sep=",")
customers = pd.read_csv("customers/part-00000-tid-2581180368179082894-038c4dab-1615-444a-994f-5a2107c4d9a8-11135734-1-c000.csv", sep=",")

country = pd.read_csv("country/part-00000-tid-5054581782199228501-41100236-b09c-46a7-8442-8d968c697e9a-11286346-1-c000.csv", sep=",")
state = pd.read_csv("state/part-00000-tid-2467726635302089596-e4fdd6ee-8624-4658-af6a-6098bc1c0825-11243350-1-c000.csv", sep=",")
city = pd.read_csv("city/part-00000-tid-7257851286237664629-906ff0c6-51c7-4cdd-97cd-dc0aa92a92f1-11185485-1-c000.csv", sep=",")

d_time = pd.read_csv("d_time/part-00000-tid-2902183611695287462-3111e3e9-023d-4533-a7e5-d0b87fb1a808-10662337-1-c000.csv", sep=",")
d_year = pd.read_csv("d_year/part-00000-tid-5440254676189819830-69d9a28f-dbd2-48ca-9eca-66f1ddb276df-10961064-1-c000.csv", sep=",")
d_month = pd.read_csv("d_month/part-00000-tid-1411108534556725179-0fbf435f-dd8b-411e-ae97-11e74b345b4f-10859988-1-c000.csv", sep=",")
d_week = pd.read_csv("d_week/part-00000-tid-8944900144231406848-ea4ff673-508c-46e0-ac10-e488037f37c5-10733320-1-c000.csv", sep=",")
d_weekday = pd.read_csv("d_weekday/part-00000-tid-1198883628307677355-d7f0c6f5-b5f5-40c6-9537-2951b88849eb-10926413-1-c000.csv", sep=",")

pix_movements = pd.read_csv("pix_movements/part-00000-tid-8322739320471544484-12382b61-f87b-4388-931d-ec1681d2aad1-10545794-1-c000.csv", sep=",")
transfer_ins = pd.read_csv("transfer_ins/part-00000-tid-3939740088886661710-b68a1bdc-ca76-4934-b2fd-756b973d041f-10414417-1-c000.csv", sep=",")
transfer_outs = pd.read_csv("transfer_outs/part-00000-tid-3880462020784336524-8a5c83e1-e1e4-471e-9dbf-1b37babaff47-10468383-1-c000.csv", sep=",")

<span style="font-family: Calibri; font-size: 14px;"> 
Quickly check of data structure and values
</span>

In [ ]:
accounts

,account_id,customer_id,created_at,status,account_branch,account_check_digit,account_number
0,127700825787235152,3018741143504866816,2019-04-19T01:34:25.000Z,active,8366,3,41002
1,2074575830148960256,59542965244359240,2019-03-05T23:01:26.000Z,active,662,1,24073
2,438980267812145600,2307496449969204224,2019-11-15T14:08:48.000Z,active,2374,4,65646
3,2388678818356235264,3002379910953780736,2019-11-02T00:42:22.000Z,active,8645,6,8070
4,2646715789379666432,739453564813079168,2019-02-09T15:14:02.000Z,active,660,8,38856
...,...,...,...,...,...,...,...
3995,3316393613677342208,2949337107965035008,2019-06-15T16:43:06.000Z,active,3555,3,65573
3996,3330034378661805056,444658631133298944,2019-04-01T12:40:27.000Z,active,274,7,36733
3997,2254923943551142912,1273672948361761536,2019-05-05T07:01:15.000Z,active,9518,9,43342
3998,845371798778885120,2185756263921039872,2019-03-31T06:33:43.000Z,active,8335,8,8128
3999,704218275493551872,3332621018693219840,2019-04-09T09:53:49.000Z,active,742,8,13019

In [ ]:
customers

,customer_id,first_name,last_name,customer_city,cpf,country_name
0,3018741143504866816,Grant,Mccain,1253365031226127616,10009538300,Brasil
1,59542965244359240,Debra,Goodson,508490229825579712,62345829674,Brasil
2,2307496449969204224,Lavonne,Gilbert,3022441711756741120,45018086367,Brasil
3,3002379910953780736,Gordon,Richard,308440555366929792,86987873767,Brasil
4,739453564813079168,Geneva,Black,5855043697306583,36854357925,Brasil
...,...,...,...,...,...,...
3995,2949337107965035008,Tessie,Weishaar,3133514207207969280,68304155557,Brasil
3996,444658631133298944,Christopher,Strickland,3022441711756741120,67860548740,Brasil
3997,1273672948361761536,Jack,Zender,798176210269504000,61418807976,Brasil
3998,2185756263921039872,Susan,Given,2419983425762407936,12521540049,Brasil
3999,3332621018693219840,Raymond,Abshire,72822273209783632,26563908092,Brasil

In [ ]:
country

  country           country_id
0  Brasil  1811589392032273152

In [ ]:
# customers['country_name'].unique()  
customers['country_name'].value_counts()

country_name
Brasil    4000
Name: count, dtype: int64

In [20]:
state.sort_values("state")

   state           country_id             state_id
20    AL  1811589392032273152   478763362826876096
21    AP  1811589392032273152   923376177486181760
8     BA  1811589392032273152   350615654648688512
9     CE  1811589392032273152  2409699387609573888
7     ES  1811589392032273152  1565160282810056448
2     GO  1811589392032273152  1704490506352719360
11    MA  1811589392032273152    73234843525808128
0     MG  1811589392032273152  3090309573211341312
14    MS  1811589392032273152   626830799835729536
6     MT  1811589392032273152  1194011450428713728
16    PA  1811589392032273152  2355659330527258624
4     PB  1811589392032273152  2402308655805438464
19    PE  1811589392032273152  2431598724103076352
17    PI  1811589392032273152  2992994763560601600
12    PR  1811589392032273152  3193480059435906560
18    RJ  1811589392032273152  1943252037534108160
15    RN  1811589392032273152  2542295797061516288
5     RS  1811589392032273152  2136045840289182976
10    SC  1811589392032273152  1268940915088243712
13    SE  1811589392032273152   564934305080023488
1     SP  1811589392032273152  3253159936379173376
3     TO  1811589392032273152  2490997963670251520

In [ ]:
city

                   city             state_id              city_id
0   São José do Goiabal  3090309573211341312  2333012745884428800
1           Pederneiras  3253159936379173376  2184659546192465408
2       Augusto de Lima  3090309573211341312  1580868134171330304
3           Lagoa Santa  1704490506352719360  1962889254359325952
4        Bernardo Sayão  2490997963670251520  2365744306120669184
..                  ...                  ...                  ...
95         Rio Dos Bois  2490997963670251520  3237215569258063360
96           Porto Belo  1268940915088243712  2183212923812817152
97             Sobrália  3090309573211341312   798176210269504000
98      Tartarugalzinho   923376177486181760  2041104140958306048
99    Santa fé de Goiás  1704490506352719360   996668673221257088

[100 rows x 3 columns]

In [ ]:
d_time

,time_id,action_timestamp,week_id,month_id,year_id,weekday_id
0,1593136311,2020-06-26T01:51:51.000Z,102426675,3042,1024140,2028
1,1596889526,2020-08-08T12:25:26.000Z,102429717,4056,1024140,2535
2,1601172264,2020-09-27T02:04:24.000Z,102433266,4563,1024140,3042
3,1596544748,2020-08-04T12:39:08.000Z,102429717,4056,1024140,507
4,1603372558,2020-10-22T13:15:58.000Z,102435294,5070,1024140,1521
...,...,...,...,...,...,...
978754,1587763196,2020-04-24T21:19:56.000Z,102422112,2028,1024140,2028
978755,1599497197,2020-09-07T16:46:37.000Z,102432252,4563,1024140,0
978756,1589591861,2020-05-16T01:17:41.000Z,102423633,2535,1024140,2535
978757,1581026390,2020-02-06T21:59:50.000Z,102416535,1014,1024140,1521
978758,1585404905,2020-03-28T14:15:05.000Z,102420084,1521,1024140,2535

In [ ]:
d_year

   year_id  action_year
0  1024140         2020

In [19]:
d_month.sort_values("action_month")

    month_id  action_month
10       507             1
8       1014             2
7       1521             3
9       2028             4
6       2535             5
0       3042             6
5       3549             7
1       4056             8
2       4563             9
3       5070            10
11      5577            11
4       6084            12

In [27]:
# d_week.sort_values("action_week").head
d_week.head()

     week_id  action_week
0  102426675       202025
1  102429717       202031
2  102433266       202038
3  102435294       202042
4  102438336       202048

In [10]:
d_week.shape

(53, 2)

In [21]:
d_weekday.sort_values("action_weekday")

   weekday_id  action_weekday
5           0               0
3         507               1
6        1014               2
4        1521               3
0        2028               4
1        2535               5
2        3042               6

In [ ]:
pix_movements

,id,account_id,pix_amount,pix_requested_at,pix_completed_at,status,in_or_out
0,3101512580483427328,127700825787235152,1.56,1587921566,NaN,failed,pix_in
1,2678169777048716288,2074575830148960256,197.16,1593136303,1.593136e+09,completed,pix_in
2,869785443623607552,2388678818356235264,422.19,1596889520,1.596890e+09,completed,pix_in
3,727767235192291200,1152700769026362752,465.36,1603372554,1.603373e+09,completed,pix_out
4,1492667345435250944,1431539955275996672,1515.34,1597414796,NaN,failed,pix_in
...,...,...,...,...,...,...,...
250343,3084456972166512128,704218275493551872,1954.46,1601953793,1.601954e+09,completed,pix_in
250344,2672867912772939776,704218275493551872,619.06,1592269516,1.592270e+09,completed,pix_out
250345,2595717889402730496,704218275493551872,688.08,1578167793,1.578168e+09,completed,pix_in
250346,1087375669976406400,704218275493551872,656.59,1602443689,1.602444e+09,completed,pix_out
250347,2894014915273887744,704218275493551872,1791.11,1588889660,1.588890e+09,completed,pix_in

In [ ]:
transfer_ins

,id,account_id,amount,transaction_requested_at,transaction_completed_at,status
0,1783896702851019520,2646715789379666432,1060.66,1601172258,1.601172e+09,completed
1,1660670504873856768,39719195379360320,1465.36,1596544739,1.596545e+09,completed
2,2875190090279428608,2388965041970796544,459.63,1592831147,1.592831e+09,completed
3,2948681858559168000,412510466362772032,755.51,1593764887,1.593765e+09,completed
4,3203557528300659200,3138902864818696704,347.74,1602115452,1.602115e+09,completed
...,...,...,...,...,...,...
174989,672295616598620800,704218275493551872,531.62,1604507117,1.604507e+09,completed
174990,924264955922369408,704218275493551872,16.85,1591850494,1.591851e+09,completed
174991,309768489783235328,704218275493551872,731.47,1584950539,1.584951e+09,completed
174992,1571712975096860928,704218275493551872,1588.30,1601499081,1.601499e+09,completed
174993,1741765065220373504,704218275493551872,725.18,1586445815,1.586446e+09,completed

In [ ]:
transfer_outs

,id,account_id,amount,transaction_requested_at,transaction_completed_at,status
0,937196074244976512,438980267812145600,1396.64,1579074367,NaN,failed
1,242838712073085184,253931865368420288,1684.49,1595144491,1.595144e+09,completed
2,135519494068348464,1410463889223333888,357.91,1580605502,1.580606e+09,completed
3,2796000684688832000,967032139408421376,1933.77,1580938498,1.580939e+09,completed
4,2362495920543102464,479529564765572288,348.90,1578923002,1.578923e+09,completed
...,...,...,...,...,...,...
75113,3226098162419468800,704218275493551872,1223.23,1585484699,1.585485e+09,completed
75114,1999685576946599680,704218275493551872,648.84,1578828308,1.578828e+09,completed
75115,1639722859682439936,704218275493551872,1078.03,1603281653,1.603282e+09,completed
75116,1989593152198824448,704218275493551872,1419.33,1583921672,1.583922e+09,completed
75117,265592258120398368,704218275493551872,1113.50,1587386894,1.587387e+09,completed

<span style="font-family: Calibri; font-size: 14px;"> 
Connecting to 'nubank' database created in SQL Server
</span>

In [ ]:
# Creating a new database
conn = pyodbc.connect(
    "DRIVER={SQL Server};SERVER=localhost\\SQLEXPRESS;DATABASE=master;Trusted_Connection=yes"
)
conn.autocommit = True 

cursor = conn.cursor()

cursor.execute("CREATE DATABASE nubank")
print("Banco criado!")

Banco criado!

In [ ]:
engine = create_engine(
    "mssql+pyodbc://localhost\\SQLEXPRESS/nubank?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

# ALTER AUTHORIZATION ON DATABASE::nubank TO sa; # to be consider when creating a SSMS diagram

<span style="font-family: Calibri; font-size: 14px;"> 
Loading DataFrames into tables in the new database
</span>

In [ ]:
accounts.to_sql("accounts", engine, index=False, if_exists="replace")
customers.to_sql("customers", engine, index=False, if_exists="replace")

city.to_sql("city", engine, index=False, if_exists="replace")
state.to_sql("state", engine, index=False, if_exists="replace")
country.to_sql("country", engine, index=False, if_exists="replace")

d_time.to_sql("d_time", engine, index=False, if_exists="replace")
d_year.to_sql("d_year", engine, index=False, if_exists="replace")
d_month.to_sql("d_month", engine, index=False, if_exists="replace")
d_week.to_sql("d_week", engine, index=False, if_exists="replace")
d_weekday.to_sql("d_weekday", engine, index=False, if_exists="replace")

pix_movements.to_sql("pix_movements", engine, index=False, if_exists="replace")
transfer_ins.to_sql("transfer_ins", engine, index=False, if_exists="replace")
transfer_outs.to_sql("transfer_outs", engine, index=False, if_exists="replace")

<span style="font-family: Calibri; font-size: 14px;"> 
Running test queries on new database tables
</span>

In [16]:
query = "SELECT * FROM accounts"
df = pd.read_sql(query, engine)
df

,account_id,customer_id,created_at,status,account_branch,account_check_digit,account_number
0,623509224135263,1143987877613632512,2019-08-13T21:34:05.000Z,active,9457,1,61733
1,1910868644230470,89245138572285488,2019-12-06T19:31:07.000Z,active,5355,4,95934
2,1963067196365885,217126971097269568,2019-06-25T07:08:35.000Z,active,8933,8,94312
3,1977223077647860,2876604376569286656,2019-07-28T08:40:50.000Z,active,7346,2,77904
4,3417018705901279,1496997014177191936,2019-10-12T18:37:14.000Z,active,91,6,9605
...,...,...,...,...,...,...,...
3995,3394753846512991232,3371411609789820928,2019-04-09T15:15:46.000Z,active,3024,4,87433
3996,3400724907247037440,718614941374023424,2019-11-18T04:50:37.000Z,active,8232,9,84562
3997,3400794439747409408,2781030536103856640,2019-05-09T01:54:50.000Z,active,5674,9,90076
3998,3401060284510745088,2246748792909592832,2019-12-24T02:17:54.000Z,active,543,9,34125
3999,3401747611611359232,724279389951473408,2019-05-06T16:34:43.000Z,active,6276,9,11047

<span style="font-family: Calibri; font-size: 14px;"> 
Creating relationships between tables, following the guidelines in the file <strong>tables_diagram.txt</strong>
</span>

In [ ]:
# Ref: state.country_id > country.country_id
# Ref: city.state_id > state.state_id

with engine.connect() as conn:   
    conn.execute(text("""ALTER TABLE country ALTER COLUMN country_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE state ALTER COLUMN state_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE city ALTER COLUMN city_id BIGINT NOT NULL"""))
    
    # Primary key
    conn.execute(text("""
        ALTER TABLE country
        ADD CONSTRAINT pk_country_id
        PRIMARY KEY (country_id)
    """))
    
    conn.execute(text("""
        ALTER TABLE state
        ADD CONSTRAINT pk_state_id
        PRIMARY KEY (state_id)
    """))
    
    conn.execute(text("""
        ALTER TABLE city
        ADD CONSTRAINT pk_city_id
        PRIMARY KEY (city_id)
    """))
    
    # Foreign key
    conn.execute(text("""
        ALTER TABLE state
        ADD CONSTRAINT fk_state_country
        FOREIGN KEY (country_id) REFERENCES country(country_id)
    """))

    conn.execute(text("""
        ALTER TABLE city
        ADD CONSTRAINT fk_city_state
        FOREIGN KEY (state_id) REFERENCES state(state_id)
    """))
    
    conn.commit()

In [ ]:
# Ref: customers.customer_city > city.city_id
# Ref: accounts.customer_id - customers.customer_id

with engine.connect() as conn:   
    conn.execute(text("""ALTER TABLE accounts ALTER COLUMN account_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE customers ALTER COLUMN customer_id BIGINT NOT NULL"""))
    
    # Primary key
    conn.execute(text("""
        ALTER TABLE accounts
        ADD CONSTRAINT pk_account_id
        PRIMARY KEY (account_id)
    """))
    
    conn.execute(text("""
        ALTER TABLE customers
        ADD CONSTRAINT pk_customer_id
        PRIMARY KEY (customer_id)
    """))
    
    # Foreign key
    conn.execute(text(""" 
        ALTER TABLE accounts
        ADD CONSTRAINT fk_account_customer
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
    """)) 

    conn.execute(text("""
        ALTER TABLE customers
        ADD CONSTRAINT fk_customer_city
        FOREIGN KEY (customer_city) REFERENCES city(city_id)
    """))

    conn.commit()

In [ ]:
# Ref: transfer_ins.account_id > accounts.account_id
# Ref: transfer_outs.account_id > accounts.account_id
# Ref: pix_movements.account_id > accounts.account_id

with engine.connect() as conn:   
    conn.execute(text("""ALTER TABLE transfer_ins ALTER COLUMN id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE transfer_outs ALTER COLUMN id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE pix_movements ALTER COLUMN id BIGINT NOT NULL"""))
    
    # Primary key
    conn.execute(text("""
        ALTER TABLE transfer_ins
        ADD CONSTRAINT pk_transfer_ins_id
        PRIMARY KEY (id)
    """))
    
    conn.execute(text("""
        ALTER TABLE transfer_outs
        ADD CONSTRAINT pk_transfer_outs_id
        PRIMARY KEY (id)
    """))

    conn.execute(text("""
        ALTER TABLE pix_movements
        ADD CONSTRAINT pk_pix_movements_id
        PRIMARY KEY (id)
    """))
    
    # Foreign key
    conn.execute(text("""
        ALTER TABLE transfer_ins
        ADD CONSTRAINT fk_transfer_ins_account
        FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    """))

    conn.execute(text("""
        ALTER TABLE transfer_outs
        ADD CONSTRAINT fk_transfer_outs_account
        FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    """))

    conn.execute(text("""
        ALTER TABLE pix_movements
        ADD CONSTRAINT fk_pix_movements_account
        FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    """))
    
    conn.commit()

In [ ]:
# Ref: d_time.week_id > d_week.week_id
# Ref: d_time.month_id > d_month.month_id
# Ref: d_time.year_id > d_year.year_id
# Ref: d_time.weekday_id > d_weekday.weekday_id

with engine.connect() as conn:
    conn.execute(text("""ALTER TABLE d_time ALTER COLUMN time_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE d_week ALTER COLUMN week_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE d_weekday ALTER COLUMN weekday_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE d_month ALTER COLUMN month_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE d_year ALTER COLUMN year_id BIGINT NOT NULL"""))

    # Primary key
    conn.execute(text("""
        ALTER TABLE d_time
        ADD CONSTRAINT pk_d_time_id
        PRIMARY KEY (time_id)
    """))
    
    conn.execute(text("""
        ALTER TABLE d_week
        ADD CONSTRAINT pk_d_week_id
        PRIMARY KEY (week_id)
    """))

    conn.execute(text("""
        ALTER TABLE d_weekday
        ADD CONSTRAINT pk_d_weekday_id
        PRIMARY KEY (weekday_id)
    """))

    conn.execute(text("""
        ALTER TABLE d_month
        ADD CONSTRAINT pk_d_month_id
        PRIMARY KEY (month_id)
    """))

    conn.execute(text("""
        ALTER TABLE d_year
        ADD CONSTRAINT pk_d_year_id
        PRIMARY KEY (year_id)
    """))

    # Foreign key
    conn.execute(text("""
        ALTER TABLE d_time
        ADD CONSTRAINT fk_d_time_week_id
        FOREIGN KEY (week_id) REFERENCES d_week(week_id)
    """))

    conn.execute(text("""
        ALTER TABLE d_time
        ADD CONSTRAINT fk_d_time_month_id
        FOREIGN KEY (month_id) REFERENCES d_month(month_id)
    """))

    conn.execute(text("""
        ALTER TABLE d_time
        ADD CONSTRAINT fk_d_time_year_id
        FOREIGN KEY (year_id) REFERENCES d_year(year_id)
    """))

    conn.execute(text("""
        ALTER TABLE d_time
        ADD CONSTRAINT fk_d_time_weekday_id
        FOREIGN KEY (weekday_id) REFERENCES d_weekday(weekday_id)
    """))

    conn.commit()

In [ ]:
# Ref: transfer_outs.transaction_requested_at > d_time.time_id
# Ref: transfer_outs.transaction_completed_at > d_time.time_id

with engine.connect() as conn:
    conn.execute(text("""ALTER TABLE transfer_outs ALTER COLUMN transaction_requested_at BIGINT"""))
    conn.execute(text("""ALTER TABLE transfer_outs ALTER COLUMN transaction_completed_at BIGINT"""))
    
    # Foreign key
    conn.execute(text("""
        ALTER TABLE transfer_outs
        ADD CONSTRAINT fk_transfer_outs_transaction_requested_at
        FOREIGN KEY (transaction_requested_at) REFERENCES d_time(time_id)
    """))

    conn.execute(text("""
        ALTER TABLE transfer_outs
        ADD CONSTRAINT fk_transfer_outs_transaction_completed_at
        FOREIGN KEY (transaction_completed_at) REFERENCES d_time(time_id)
    """))

    conn.commit()

In [28]:
# Ref: transfer_ins.transaction_requested_at > d_time.time_id
# Ref: transfer_ins.transaction_completed_at > d_time.time_id

with engine.connect() as conn:
    conn.execute(text("""ALTER TABLE transfer_ins ALTER COLUMN transaction_requested_at BIGINT"""))
    conn.execute(text("""ALTER TABLE transfer_ins ALTER COLUMN transaction_completed_at BIGINT"""))

    # Foreign key
    conn.execute(text("""
        ALTER TABLE transfer_ins
        ADD CONSTRAINT fk_transfer_ins_transaction_requested_at
        FOREIGN KEY (transaction_requested_at) REFERENCES d_time(time_id)
    """))

    conn.execute(text("""
        ALTER TABLE transfer_ins
        ADD CONSTRAINT fk_transfer_ins_transaction_completed_at
        FOREIGN KEY (transaction_completed_at) REFERENCES d_time(time_id)
    """))

    conn.commit()

In [30]:
# Ref: pix_movements.pix_requested_at > d_time.time_id
# Ref: pix_movements.pix_completed_at > d_time.time_id

with engine.connect() as conn:
    conn.execute(text("""ALTER TABLE pix_movements ALTER COLUMN pix_requested_at BIGINT"""))
    conn.execute(text("""ALTER TABLE pix_movements ALTER COLUMN pix_completed_at BIGINT"""))

    # Foreign key
    conn.execute(text("""
        ALTER TABLE pix_movements
        ADD CONSTRAINT fk_pix_movements_pix_requested_at
        FOREIGN KEY (pix_requested_at) REFERENCES d_time(time_id)
    """))

    conn.execute(text("""
        ALTER TABLE pix_movements
        ADD CONSTRAINT fk_pix_movements_pix_completed_at
        FOREIGN KEY (pix_completed_at) REFERENCES d_time(time_id)
    """))
    
    conn.commit()

<span style="font-family: Calibri; font-size: 14px;"> 
<strong>
Data model proposal
</strong><br>
Creating a copy of the original database<br>
</span>

In [ ]:
# Creating a new database
conn = pyodbc.connect(
    "DRIVER={SQL Server};SERVER=localhost\\SQLEXPRESS;DATABASE=nubank;Trusted_Connection=yes"
)
conn.autocommit = True 

cursor = conn.cursor()

cursor.execute("CREATE DATABASE nubank_proposta")
print("Banco criado!")

# Generate scripts of the original database tables to be executed in the new one
cursor.execute("""
    SELECT TABLE_NAME 
    FROM nubank.INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_TYPE = 'BASE TABLE'
""")
tabelas = [row[0] for row in cursor.fetchall()]
print("Tabelas encontradas:", tabelas)

Banco criado!
Tabelas encontradas: ['sysdiagrams', 'accounts', 'customers', 'city', 'state', 'country', 'd_time', 'd_year', 'd_month', 'd_week', 'd_weekday', 'pix_movements', 'transfer_ins', 'transfer_outs']

In [ ]:
# Copy each table with structure + data
for tabela in tabelas:
    if tabela == 'sysdiagrams':
        continue  # ignore system table
    
    try:
        cursor.execute(f"""
            SELECT * INTO nubank_proposta.dbo.{tabela}
            FROM nubank.dbo.{tabela}
        """)
        
        # Count records in the new table
        cursor.execute(f"SELECT COUNT(*) FROM nubank_proposta.dbo.{tabela}")
        count = cursor.fetchone()[0]
        print(f"✅ {tabela}: {count} registros copiados")
        
    except Exception as e:
        print(f"❌ {tabela}: {e}")

print("\nCópia concluída!")

✅ accounts: 4000 registros copiados
✅ customers: 4000 registros copiados
✅ city: 100 registros copiados
✅ state: 22 registros copiados
✅ country: 1 registros copiados
✅ d_time: 978759 registros copiados
✅ d_year: 1 registros copiados
✅ d_month: 12 registros copiados
✅ d_week: 53 registros copiados
✅ d_weekday: 7 registros copiados
✅ pix_movements: 250348 registros copiados
✅ transfer_ins: 174994 registros copiados
✅ transfer_outs: 75118 registros copiados

Cópia concluída!

In [36]:
cursor.execute("SELECT DB_NAME() AS banco_atual")
print(cursor.fetchone().banco_atual)

nubank

In [5]:
cursor.execute("USE nubank_proposta")

In [7]:
cursor.execute("SELECT DB_NAME() AS banco_atual")
print(cursor.fetchone().banco_atual)

nubank_proposta

<span style="font-family: Calibri; font-size: 14px;"> 
Proposed changes to the current data model in a homologation environment (using a copy of the database)
</span>

In [2]:
engine = create_engine(
    "mssql+pyodbc://localhost\\SQLEXPRESS/nubank_proposta?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

# ALTER AUTHORIZATION ON DATABASE::nubank_proposta TO sa; # to be consider when creating a SSMS diagram

In [ ]:
with engine.connect() as conn:
    # Delete column country_name, as it is redundant with the relationships between city, state and country tables and can lead to inconsistencies in the future
    conn.execute(text("""ALTER TABLE customers DROP COLUMN country_name""")) 
    
    # Rename column customer_city to city_id, to make it more clear that it is a foreign key to the city table and to follow naming conventions
    conn.execute(text("""
        EXEC sp_rename 'customers.customer_city', 'city_id', 'COLUMN'  
    """)) 
    
    # Changes to the customers table, to improve flexibility for different document types across countries, and to prevent data inconsistencies
    conn.execute(text("""
        EXEC sp_rename 'customers.cpf', 'document_number', 'COLUMN'  
    """))
   
    conn.execute(text("""ALTER TABLE customers ADD document_type VARCHAR(500)""")) 
    
    conn.execute(text("""UPDATE customers SET document_type = 'CPF' WHERE document_number IS NOT NULL""")) 

    # Delete tables/columns that assist in d_time, as values are already legible integers in the action_timestamp column and can be query by date functions
    conn.execute(text("""DROP TABLE d_week""")) 
    conn.execute(text("""DROP TABLE d_month""")) 
    conn.execute(text("""DROP TABLE d_weekday""")) 
    conn.execute(text("""DROP TABLE d_year""")) 
    
    conn.execute(text("""ALTER TABLE d_time DROP COLUMN week_id""")) 
    conn.execute(text("""ALTER TABLE d_time DROP COLUMN weekday_id""")) 
    conn.execute(text("""ALTER TABLE d_time DROP COLUMN month_id""")) 
    conn.execute(text("""ALTER TABLE d_time DROP COLUMN year_id""")) 
    
    conn.execute(text("""ALTER TABLE d_time ADD action_year INT""")) 
    conn.execute(text("""ALTER TABLE d_time ADD action_month INT""")) 
    conn.execute(text("""ALTER TABLE d_time ADD action_week INT""")) 
    conn.execute(text("""ALTER TABLE d_time ADD action_weekday INT""")) 
	
    conn.execute(text("""UPDATE d_time SET action_year = DATEPART(year,action_timestamp) """)) 
    conn.execute(text("""UPDATE d_time SET action_month = DATEPART(month,action_timestamp) """)) 
    conn.execute(text("""UPDATE d_time SET action_week = CAST(YEAR(action_timestamp) AS VARCHAR) + RIGHT('0' + CAST(DATEPART(ISO_WEEK, action_timestamp) - 1 AS VARCHAR), 2) """)) 
    conn.execute(text("""UPDATE d_time SET action_weekday = (DATEPART(weekday, action_timestamp) + @@DATEFIRST - 2 + 7) % 7  """)) 

    # New tables for transactions and products, enabling the addition of new types of movements in the future.
    conn.execute(text("""create table products (product_id BIGINT PRIMARY KEY, product_name VARCHAR(255), country_id BIGINT""")) 

    conn.execute(text("""INSERT INTO products VALUES ('1','Pix Movements', 1811589392032273152)""")) 
    conn.execute(text("""INSERT INTO products VALUES ('2','Transfer Movements', 1811589392032273152)""")) 
        
    conn.execute(text("""create table transactions_type (
					  transaction_type_id BIGINT PRIMARY KEY, 
					  description VARCHAR(255)
                      )
					  """)) 

    conn.execute(text("""INSERT INTO transactions_type VALUES ('11','pix_in')""")) 
    conn.execute(text("""INSERT INTO transactions_type VALUES ('12','pix_out')""")) 
    conn.execute(text("""INSERT INTO transactions_type VALUES ('21','transfer_in')""")) 
    conn.execute(text("""INSERT INTO transactions_type VALUES ('22','transfer_out')""")) 
    
    conn.execute(text("""create table transactions (
					  transaction_id BIGINT PRIMARY KEY, 
					  account_id BIGINT,
					  product_id BIGINT,
                      amount DECIMAL(18,2), 
					  transaction_type_id BIGINT,
                      transaction_requested_at BIGINT,
                      transaction_completed_at BIGINT,
                      transaction_status VARCHAR(50),
                      currency VARCHAR(10)
                      )
					  """)) 

    conn.execute(text("""insert into transactions  
        select id, account_id, 2 as product_id, amount, 21 as transaction_type_id,  transaction_requested_at , transaction_completed_at, status , 'BRL' as currency
        from transfer_ins
        union all 
        select id, account_id, 2 as product_id, amount, 22 as transaction_type_id,  transaction_requested_at, transaction_completed_at, status , 'BRL' as currency
        from transfer_outs
        union all 
        select id, account_id, 1 as product_id, pix_amount, case when in_or_out = 'pix_in' then 11 else 12 end as transaction_type_id,  pix_requested_at, pix_completed_at, status , 'BRL' as currency
        from pix_movements""")) 
    
    conn.execute(text("""DROP TABLE pix_movements""")) 
    conn.execute(text("""DROP TABLE transfer_outs""")) 
    conn.execute(text("""DROP TABLE transfer_ins""")) 

    conn.commit()

<span style="font-family: Calibri; font-size: 14px;"> 
Validating changes
</span>

In [15]:
# customers

query = """
  SELECT TOP (1000) 
       a.customer_id
      ,a.first_name
      ,a.last_name
      ,a.city_id 
      ,a.document_number 
      ,a.document_type 
      --,a.country_name
      ,d.country as country_name 
  FROM nubank_proposta.dbo.customers    as a 
  LEFT JOIN nubank_proposta.dbo.city    as b on a.city_id    = b.city_id 
  LEFT JOIN nubank_proposta.dbo.state   as c on b.state_id   = c.state_id 
  LEFT JOIN nubank_proposta.dbo.country as d on c.country_id = d.country_id
"""
df = pd.read_sql(query, engine)
df

,customer_id,first_name,last_name,city_id,document_number,document_type,country_name
0,158554461894233,Rosemary,Haynes,336249655379697984,61733221860,CPF,Brasil
1,1195719066794785,David,Gibson,3065955382848678912,3061598443,CPF,Brasil
2,1224030529509161,Marlene,Greenfield,1298948914652025344,95690672593,CPF,Brasil
3,1643026787581571,Antoine,Free,1580868134171330304,261149495,CPF,Brasil
4,2729188736308849,Stacy,Laymon,648580340723423232,89698937168,CPF,Brasil
...,...,...,...,...,...,...,...
995,810736911063121920,Phyllis,Nelson,903515599400755072,23395725137,CPF,Brasil
996,810906841569322240,Toni,Markham,1962889254359325952,62289346069,CPF,Brasil
997,811136329041355776,Kiley,Orphey,1298948914652025344,80822539852,CPF,Brasil
998,811508290345381632,Pia,Smith,2365744306120669184,62687072305,CPF,Brasil
999,811617788423618816,Tasha,Allen,1671822576895199744,24830745092,CPF,Brasil

In [ ]:
# d_time

query = """
  SELECT *
     -- distinct 
	 -- b.action_week
	 -- ,c.action_weekday
	 -- ,d.action_month
	 -- ,e.action_year
	 --  cast(a.action_timestamp as date) as action_date
	 -- ,DATEPART(month,action_timestamp) as action_month
	 -- ,DATEPART(year,action_timestamp) as action_year
     -- ,CAST(YEAR(action_timestamp) AS VARCHAR) + RIGHT('0' + CAST(DATEPART(ISO_WEEK, action_timestamp) - 1 AS VARCHAR), 2) AS action_week
	 -- ,(DATEPART(weekday, action_timestamp) + @@DATEFIRST - 2 + 7) % 7 AS action_weekday -- starting on monday, 0-6
  FROM nubank_proposta.dbo.d_time a 
 -- left join d_week b on a.week_id = b.week_id
 -- left join d_weekday c on a.weekday_id = c.weekday_id
 -- left join d_month d on a.month_id = d.month_id
 -- left join d_year e on a.year_id = e.year_id
  order by cast(a.action_timestamp as date) 
"""
df = pd.read_sql(query, engine)
df

,time_id,action_timestamp,action_year,action_month,action_week,action_weekday
0,1577836802,2020-01-01T00:00:02.000Z,2020,1,202000,2
1,1577836805,2020-01-01T00:00:05.000Z,2020,1,202000,2
2,1577836834,2020-01-01T00:00:34.000Z,2020,1,202000,2
3,1577836844,2020-01-01T00:00:44.000Z,2020,1,202000,2
4,1577836896,2020-01-01T00:01:36.000Z,2020,1,202000,2
...,...,...,...,...,...,...
978754,1609459041,2020-12-31T23:57:21.000Z,2020,12,202052,3
978755,1609459054,2020-12-31T23:57:34.000Z,2020,12,202052,3
978756,1609459062,2020-12-31T23:57:42.000Z,2020,12,202052,3
978757,1609459093,2020-12-31T23:58:13.000Z,2020,12,202052,3
978758,1609459106,2020-12-31T23:58:26.000Z,2020,12,202052,3

In [12]:
# products

query = """
  SELECT * from products
"""
df = pd.read_sql(query, engine)
df

   product_id        product_name           country_id
0           1       Pix Movements  1811589392032273152
1           2  Transfer Movements  1811589392032273152

In [50]:
# transactions_type

query = """
  SELECT * from transactions_type
"""
df = pd.read_sql(query, engine)
df

   transaction_type_id   description
0                   11        pix_in
1                   12       pix_out
2                   21   transfer_in
3                   22  transfer_out

In [6]:
# transactions

query = """
  SELECT  
  transaction_id, account_id, product_id, transaction_type_id, transaction_requested_at, transaction_completed_at, transaction_status, amount, currency
  from transactions
"""
df = pd.read_sql(query, engine)
df

,transaction_id,account_id,product_id,transaction_type_id,transaction_requested_at,transaction_completed_at,transaction_status,amount,currency
0,1905526228328,3344350342360918528,2,21,1592237266,NaN,failed,1825.14,BRL
1,8050018111488,436078529800937088,1,11,1589037217,1.589037e+09,completed,1982.46,BRL
2,15468786971758,3386401529082005504,2,21,1609200019,1.609200e+09,completed,1866.63,BRL
3,21047734532096,196118294852870752,2,21,1606417136,1.606417e+09,completed,448.48,BRL
4,21538059756947,2049854582898863360,2,22,1579355316,1.579355e+09,completed,1797.07,BRL
...,...,...,...,...,...,...,...,...,...
500455,3402811221264279552,49447840776902688,2,22,1597266514,1.597267e+09,completed,444.20,BRL
500456,3402811438383354880,3251023429694187008,1,11,1607396825,1.607397e+09,completed,1390.47,BRL
500457,3402817623509785600,1670685025093598208,2,21,1603383090,1.603383e+09,completed,840.20,BRL
500458,3402819480072835072,3189881699920608768,1,11,1584020496,1.584020e+09,completed,388.77,BRL
500459,3402821787374119424,1445575213760933120,2,21,1597197793,1.597198e+09,completed,416.68,BRL

<span style="font-family: Calibri; font-size: 14px;"> 
Creating relationships between tables
</span>

In [ ]:
# Ref: state.country_id > country.country_id
# Ref: city.state_id > state.state_id

with engine.connect() as conn:   
    conn.execute(text("""ALTER TABLE country ALTER COLUMN country_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE state ALTER COLUMN state_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE city ALTER COLUMN city_id BIGINT NOT NULL"""))
    
    # Primary key
    conn.execute(text("""
        ALTER TABLE country
        ADD CONSTRAINT pk_country_id
        PRIMARY KEY (country_id)
    """))
    
    conn.execute(text("""
        ALTER TABLE state
        ADD CONSTRAINT pk_state_id
        PRIMARY KEY (state_id)
    """))
    
    conn.execute(text("""
        ALTER TABLE city
        ADD CONSTRAINT pk_city_id
        PRIMARY KEY (city_id)
    """))
    
    # Foreign key
    conn.execute(text("""
        ALTER TABLE state
        ADD CONSTRAINT fk_state_country
        FOREIGN KEY (country_id) REFERENCES country(country_id)
    """))

    conn.execute(text("""
        ALTER TABLE city
        ADD CONSTRAINT fk_city_state
        FOREIGN KEY (state_id) REFERENCES state(state_id)
    """))
    
    conn.commit()

In [ ]:
# Ref: customers.customer_city > city.city_id
# Ref: accounts.customer_id - customers.customer_id

with engine.connect() as conn:   
    conn.execute(text("""ALTER TABLE accounts ALTER COLUMN account_id BIGINT NOT NULL"""))
    conn.execute(text("""ALTER TABLE customers ALTER COLUMN customer_id BIGINT NOT NULL"""))
    
    # Primary key
    conn.execute(text("""
        ALTER TABLE accounts
        ADD CONSTRAINT pk_account_id
        PRIMARY KEY (account_id)
    """))
    
    conn.execute(text("""
        ALTER TABLE customers
        ADD CONSTRAINT pk_customer_id
        PRIMARY KEY (customer_id)
    """))
    
    # Foreign key
    conn.execute(text(""" 
        ALTER TABLE accounts
        ADD CONSTRAINT fk_account_customer
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
    """)) 

    conn.execute(text("""
        ALTER TABLE customers
        ADD CONSTRAINT fk_customer_city
        FOREIGN KEY (city_id) REFERENCES city(city_id)
    """))

    conn.commit()

In [ ]:
# Ref: transactions.transaction_type_id > transactions_type.transaction_type_id
# Ref: transactions.product_id > products.product_id
# Ref: transactions.account_id > accounts.account_id
# Ref: transactions.transaction_requested_at > d_time.transaction_requested_at
# Ref: transactions.transaction_completed_at > d_time.transaction_completed_at

with engine.connect() as conn:      
    conn.execute(text("""ALTER TABLE d_time ALTER COLUMN time_id BIGINT NOT NULL"""))

    # Primary key
    conn.execute(text("""
        ALTER TABLE d_time
        ADD CONSTRAINT pk_d_time_id
        PRIMARY KEY (time_id)
    """))
     
    # Foreign key
    conn.execute(text(""" 
        ALTER TABLE transactions
        ADD CONSTRAINT fk_transaction_type
        FOREIGN KEY (transaction_type_id) REFERENCES transactions_type(transaction_type_id)
    """)) 

    conn.execute(text("""
        ALTER TABLE transactions
        ADD CONSTRAINT fk_transaction_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
    """))

    conn.execute(text("""
        ALTER TABLE transactions
        ADD CONSTRAINT fk_transaction_account
        FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    """))

    conn.execute(text("""
        ALTER TABLE transactions
        ADD CONSTRAINT fk_transactions_transaction_requested_at
        FOREIGN KEY (transaction_requested_at) REFERENCES d_time(time_id)
    """))

    conn.execute(text("""
        ALTER TABLE transactions
        ADD CONSTRAINT fk_transactions_transaction_completed_at
        FOREIGN KEY (transaction_completed_at) REFERENCES d_time(time_id)
    """))
    
    conn.execute(text("""
        ALTER TABLE products
        ADD CONSTRAINT fk_products_country
        FOREIGN KEY (country_id) REFERENCES country(country_id)
    """))

    conn.commit()